"""Type stubs for the compiled maskforge._native extension (0.1.0 surface)."""

from typing import Iterable, Sequence

class MaskforgeError(Exception):
    args: tuple[object, ...]
    code: str
    stage: str
    pointer: str | None
    keyword: str | None
    observed: object | None
    message: str
    limit: object | None

class PySchemaIR:
    def is_supported(self) -> bool: ...
    def diagnostics(self) -> list[tuple[str, str | None]]: ...
    def node_count(self) -> int: ...
    def ir_version(self) -> int: ...
    def canonical_hash(self) -> bytes: ...
    def to_wire(self) -> bytes: ...
    def requires_structured_backend(self) -> bool: ...

class PyVocabulary:
    def __init__(
        self,
        eos_token_id: int,
        tokens: Iterable[tuple[bytes, Sequence[int]]],
        logits_vocab_size: int | None = ...,
    ) -> None: ...
    @staticmethod
    def from_id_ordered_tokens(
        decoded_tokens: Sequence[bytes | None],
        eos_token_id: int,
        logits_vocab_size: int | None = ...,
    ) -> "PyVocabulary": ...
    @staticmethod
    def from_tokenizer_json(
        tokenizer_json: str,
        eos_token_id: int,
        logits_vocab_size: int | None = ...,
    ) -> "PyVocabulary": ...
    @staticmethod
    def from_packed_buffers(
        token_bytes: object,
        byte_offsets: object,
        token_ids: object,
        id_offsets: object,
        eos_token_id: int,
        logits_vocab_size: int | None = ...,
    ) -> "PyVocabulary": ...
    def mask_vocab_size(self) -> int: ...
    def eos_token_id(self) -> int: ...
    def len(self) -> int: ...
    def fingerprint(self) -> bytes: ...
    def artifact_cache_stats(self) -> tuple[int, int, int, int, int, int]: ...
    def clear_artifact_cache(self) -> None: ...

class PyIndex:
    def start(self) -> int: ...
    def advance(self, state: int, token_id: int) -> int: ...
    def is_accepting(self, state: int) -> bool: ...
    def is_dead(self, state: int) -> bool: ...
    def mask_word_into_state(self, state: int, out: bytearray) -> None: ...
    def mask_words(self, states: Sequence[int], rows: Sequence[int] | None) -> list[int]: ...

class PyMaskTableView:
    """Read-only zero-copy packed mask table; supports the buffer protocol (e.g. numpy.asarray)."""

    row_count: int
    words_per_row: int
    bytes_per_row: int

class Compiler:
    def __init__(
        self,
        executable_cache_bytes: int | None = ...,
        trie_cache_bytes: int | None = ...,
        bind_policy: str | None = ...,
    ) -> None: ...
    @staticmethod
    def without_cache() -> "Compiler": ...
    def compile_json_schema(self, schema: str) -> "SchemaProgram": ...
    def compile_json_schema_with_resources(
        self,
        schema: str,
        retrieval_uri: str | None = ...,
        resources: dict[str, str] | None = ...,
        max_document_bytes: int | None = ...,
        max_total_input_bytes: int | None = ...,
    ) -> "SchemaProgram": ...
    def cache_stats(self) -> tuple[int, int, int, int, int, int]: ...
    def clear_caches(self) -> None: ...

class SchemaProgram:
    def bind(self, vocabulary: "CompiledVocabulary") -> "BoundSchema": ...

class CompiledVocabulary:
    @staticmethod
    def from_vocabulary(vocabulary: PyVocabulary) -> "CompiledVocabulary": ...
    def mask_vocab_size(self) -> int: ...
    def eos_token_id(self) -> int: ...
    def token_bytes(self, token_id: int) -> bytes | None: ...

class BoundSchema:
    def start_session(self) -> "Session": ...
    def mask_word_count(self) -> int: ...
    def mask_vocab_size(self) -> int: ...
    def eos_token_id(self) -> int: ...

class Session:
    def write_mask(self, out: bytearray) -> None: ...
    def advance(self, token_id: int) -> None: ...
    def reset(self) -> None: ...
    def is_accepting(self) -> bool: ...
    def is_dead(self) -> bool: ...
    def is_stopped(self) -> bool: ...
    def mask_word_count(self) -> int: ...
    def mask_vocab_size(self) -> int: ...
    def eos_token_id(self) -> int: ...

class PyStructuredMatcher:
    def __init__(self, ir: PySchemaIR, vocabulary: PyVocabulary) -> None: ...
    def is_finished(self) -> bool: ...
    def is_dead(self) -> bool: ...
    def reset(self) -> None: ...
    def commit_token(self, token_id: int) -> bool: ...
    def compute_mask_into(self, out: bytearray) -> None: ...
    def frame_profile(self) -> tuple[int, int]: ...

def schema_to_ir(schema: str, assume_closed: bool = ...) -> PySchemaIR: ...
def schema_to_ir_with_resources(
    schema: str,
    retrieval_uri: str | None = ...,
    resources: dict[str, str] | None = ...,
    assume_closed: bool = ...,
    max_document_bytes: int | None = ...,
    max_total_input_bytes: int | None = ...,
) -> PySchemaIR: ...
def schema_to_ir_with_external_refs(schema: str, resolver: dict[str, str]) -> PySchemaIR: ...
def regex_ir(pattern: str) -> PySchemaIR: ...
def ir_from_wire(bytes_: bytes) -> PySchemaIR: ...
def compile_ir(
    ir_wire: bytes,
    eos_token_id: int,
    tokens: Iterable[tuple[bytes, list[int]]],
    bind_mode: str = ...,
    logits_vocab_size: int | None = ...,
) -> PyIndex: ...
def compile_ir_with_vocabulary(vocabulary: PyVocabulary, ir_wire: bytes, bind_mode: str) -> PyIndex: ...
def compile_json_schema(
    schema: str,
    eos_token_id: int,
    tokens: Iterable[tuple[bytes, list[int]]],
    assume_closed: bool = ...,
    bind_mode: str = ...,
    logits_vocab_size: int | None = ...,
) -> PyIndex: ...
def compile_json_schema_with_vocabulary(
    vocabulary: PyVocabulary, schema: str, assume_closed: bool = ..., bind_mode: str = ...
) -> PyIndex: ...
def configure_vocab_build_budget(max_concurrent: int, byte_budget: int) -> None: ...
def configure_vocab_serving_budget(max_concurrent: int, byte_budget: int) -> None: ...
def vocab_build_budget_stats() -> tuple[int, int, int, int]: ...
def vocab_serving_budget_stats() -> tuple[int, int, int, int]: ...
def configure_automaton_build_budget(max_concurrent: int, byte_budget: int) -> None: ...
def automaton_build_budget_stats() -> tuple[int, int, int, int]: ...
def trie_cache_stats() -> tuple[int, ...]: ...
def executable_cache_stats() -> tuple[int, int, int, int, int, int]: ...
def clear_executable_cache() -> None: ...

# test-utils build only (never present in a released wheel)
def corpus_index(
    name: str, eos_token_id: int, tokens: Iterable[tuple[bytes, list[int]]], bind_mode: str = ...
) -> PyIndex: ...
def corpus_json_schema(name: str) -> str: ...
def corpus_names() -> list[str]: ...
def corpus_samples(name: str) -> list[str]: ...
