"""Compile once, bind once per vocabulary, start a session per generation sequence."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Generic, TypeVar

from . import _native
from .constraints import OutputInput, OutputSpec, normalize

if TYPE_CHECKING:
    from .vocabulary import Vocabulary

T = TypeVar("T")

# Accepted values for Compiler(bind_policy=...); the native side rejects anything else.
BIND_POLICIES = ("adaptive", "eager", "lazy")


class Session(Generic[T]):
    """One generation sequence's mutable state. Never shared between concurrent sequences."""

    def __init__(self, native_session: Any, output_spec: OutputSpec[T]) -> None:
        self._native = native_session
        self.output_spec = output_spec

    def write_mask(self, out: bytearray) -> None:
        """Fills `out` (a bytearray of `4 * mask_word_count` bytes) with the allowed-token mask."""
        self._native.write_mask(out)

    def advance(self, token_id: int) -> None:
        """Commits one generated token to this session."""
        self._native.advance(int(token_id))

    def reset(self) -> None:
        """Returns the session to its start position, reusing the bound artifact."""
        self._native.reset()

    @property
    def is_accepting(self) -> bool:
        """True when the value generated so far is complete and valid."""
        return self._native.is_accepting()

    @property
    def is_dead(self) -> bool:
        """True when no continuation can satisfy the schema."""
        return self._native.is_dead()

    @property
    def is_stopped(self) -> bool:
        """True once EOS has been committed."""
        return self._native.is_stopped()

    @property
    def mask_word_count(self) -> int:
        """The `u32` word count a `write_mask` buffer must hold."""
        return self._native.mask_word_count()

    @property
    def mask_vocab_size(self) -> int:
        """This session's vocabulary width, in tokens."""
        return self._native.mask_vocab_size()

    @property
    def eos_token_id(self) -> int:
        """This session's EOS token id."""
        return self._native.eos_token_id()

    def parse(self, generated_utf8: bytes | bytearray | str) -> T:
        """Parses generated bytes back into this session's output type."""
        text = (
            generated_utf8.decode("utf-8")
            if isinstance(generated_utf8, (bytes, bytearray))
            else generated_utf8
        )
        return self.output_spec.parse_json(text)


class BoundSchema(Generic[T]):
    """A schema bound to one vocabulary; start as many independent sessions as needed."""

    def __init__(self, native_bound: Any, output_spec: OutputSpec[T]) -> None:
        self._native = native_bound
        self.output_spec = output_spec

    def start_session(self) -> Session[T]:
        """Starts one independent generation sequence over this bound schema."""
        return Session(self._native.start_session(), self.output_spec)

    @property
    def mask_word_count(self) -> int:
        """The `u32` word count every session's mask buffer must hold."""
        return self._native.mask_word_count()

    @property
    def mask_vocab_size(self) -> int:
        """The bound vocabulary's width, in tokens."""
        return self._native.mask_vocab_size()

    @property
    def eos_token_id(self) -> int:
        """The bound vocabulary's EOS token id."""
        return self._native.eos_token_id()


class SchemaProgram(Generic[T]):
    """A compiled schema, vocabulary-independent; reuse across every vocabulary that needs it."""

    def __init__(self, native_program: Any, output_spec: OutputSpec[T]) -> None:
        self._native = native_program
        self.output_spec = output_spec

    def bind(self, vocabulary: "Vocabulary") -> BoundSchema[T]:
        """Binds this program to one vocabulary, producing a reusable artifact."""
        return BoundSchema(self._native.bind(vocabulary._native), self.output_spec)

    def parse(self, text: str) -> T:
        """Parses generated JSON text back into this program's output type."""
        return self.output_spec.parse_json(text)


class Compiler:
    """Owns schema-compilation cache state; construct one per process or per isolated tenant."""

    def __init__(
        self,
        executable_cache_bytes: int | None = None,
        *,
        trie_cache_bytes: int | None = None,
        bind_policy: str | None = None,
    ) -> None:
        if bind_policy is not None and bind_policy not in BIND_POLICIES:
            raise ValueError(f"bind_policy must be one of {BIND_POLICIES}, got {bind_policy!r}")
        self._native = _native.Compiler(executable_cache_bytes, trie_cache_bytes, bind_policy)

    @classmethod
    def without_cache(cls) -> "Compiler":
        """A compiler that caches nothing; every compile is a fresh build."""
        self = cls.__new__(cls)
        self._native = _native.Compiler.without_cache()
        return self

    def compile(
        self,
        output_type_or_schema: OutputInput[T],
        *,
        retrieval_uri: str | None = None,
        resources: dict[str, str] | None = None,
        max_document_bytes: int | None = None,
        max_total_input_bytes: int | None = None,
    ) -> SchemaProgram[T]:
        """Normalizes the output type via OutputSpec, then compiles it."""
        spec: OutputSpec[T] = normalize(output_type_or_schema)
        if retrieval_uri is not None or resources is not None:
            native_program = self._native.compile_json_schema_with_resources(
                spec.schema_text,
                retrieval_uri=retrieval_uri,
                resources=resources,
                max_document_bytes=max_document_bytes,
                max_total_input_bytes=max_total_input_bytes,
            )
        else:
            native_program = self._native.compile_json_schema(spec.schema_text)
        return SchemaProgram(native_program, spec)

    def cache_stats(self) -> Any:
        """Current retention and cumulative traffic for this compiler's caches."""
        return self._native.cache_stats()

    def clear_caches(self) -> None:
        """Drops every cached executable and trie this compiler retains."""
        self._native.clear_caches()
